"""
Purpose
-------
Defines the contract for all Large Language Model (LLM)
implementations.

Responsibilities
----------------
- Accept a prompt.
- Generate a response.

Does NOT
--------
- Retrieve documents.
- Generate embeddings.
- Build prompts.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

# This is just like interface
class LLM(ABC):
    """
    Abstract base class for all LLM implementations.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str,
    ) -> str:
        """
        Generate a response for the supplied prompt.

        Parameters
        ----------
        prompt
            Prompt generated by a PromptBuilder.

        Returns
        -------
        str
            Generated response.
        """
        raise NotImplementedError