"""
Purpose
-------
Defines the contract for all Large Language Model (LLM)
implementations.

Responsibilities
----------------
- Accept a prompt.
- Generate a response.

Does NOT
--------
- Retrieve documents.
- Generate embeddings.
- Build prompts.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping
from typing import Any


class LLM(ABC):
    """
    Abstract base class for all LLM implementations.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str,
        options: Mapping[str, Any] | None = None,
    ) -> str:
        """
        Generate a response for the supplied prompt.

        Parameters
        ----------
        prompt
            Prompt generated by a PromptBuilder.

        options
            Provider-specific generation options.

            Examples
            --------
            - temperature
            - top_p
            - seed
            - stop
            - max_tokens

        Returns
        -------
        str
            Generated response.
        """
        raise NotImplementedError