"""
Purpose
-------
Represents the response returned by a Large Language Model (LLM).

Responsibilities
----------------
- Store the generated response text.
- Provide a stable response model for all LLM providers.

Does NOT
--------
- Generate responses.
- Store provider-specific metadata.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class LLMResponse:
    """
    Represents a response generated by an LLM.

    Attributes
    ----------
    text
        Generated response text.
    """

    content: str